### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Obinna** [McWilliamsCenter/CMUDeepLens#1]
Hi McWilliams,

The link to wget http://metcalf1.bo.astro.it/blf-portal/data/GroundBasedTraining.tar.gz is broken. 
Is there an alternative?

Thanks,

Obinna

**Comment by sarafina325** [comment]
Hi-- is there a solution to this?

Thanks,
Sarafina

**Comment by rmandelb** [comment]
@EiffL - do you know?

**Comment by EiffL** [comment]
Yes, this is unfortunate, I have noticed it a while back but have been unable to find an updated link. I need to contact the bologna people about this.

**Comment by EiffL** [comment]
Ok, this is fixed thanks to @sarafina325, thanks a lot !
