### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by JavierOrjuela** [McWilliamsCenter/CMUDeepLens#2]
Hi,
The link: 
http://metcalf1.bo.astro.it/blf-portal/data/GroundBasedTraining.tar.gz is broken. Do you have another link in which I can get the data for running your code. I'd appreciate a lot.

**Comment by EiffL** [comment]
Sorry it took a while, the link has been updated, it is now: `http://metcalf1.difa.unibo.it/blf-portal/gg_challenge.html`
